
export const ROW = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N']
export const COLUMN = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']
export const list_seat = [
    { id: 1, name: 'seat 1', row: 'A', column: '1' },
    { id: 2, name: 'seat 2', row: 'A', column: '2' },
    { id: 3, name: 'seat 3', row: 'A', column: '3' },
    { id: 4, name: 'seat 4', row: 'A', column: '4' },
    { id: 5, name: 'seat 5', row: 'A', column: '5' },
    { id: 6, name: 'seat 6', row: 'A', column: '6' },
    { id: 7, name: 'seat 7', row: 'A', column: '7' },
    { id: 8, name: 'seat 8', row: 'A', column: '8' },
    { id: 9, name: 'seat 9', row: 'A', column: '9' },
    { id: 10, name: 'seat 10', row: 'A', column: '10' },
    { id: 11, name: 'seat 11', row: 'A', column: '11' },
    { id: 12, name: 'seat 12', row: 'A', column: '12' },

    { id: 13, name: 'seat 1', row: 'B', column: '1' },
    { id: 14, name: 'seat 2', row: 'B', column: '2' },
    { id: 15, name: 'seat 3', row: 'B', column: '3' },
    { id: 16, name: 'seat 4', row: 'B', column: '4' },
    { id: 17, name: 'seat 5', row: 'B', column: '5' },
    { id: 18, name: 'seat 6', row: 'B', column: '6' },
    { id: 19, name: 'seat 7', row: 'B', column: '7' },
    { id: 20, name: 'seat 8', row: 'B', column: '8' },
    { id: 21, name: 'seat 9', row: 'B', column: '9' },
    { id: 22, name: 'seat 10', row: 'B', column: '10' },
    { id: 23, name: 'seat 11', row: 'B', column: '11' },
    { id: 24, name: 'seat 12', row: 'B', column: '12' },

    { id: 25, name: 'seat 1', row: 'C', column: '1' },
    { id: 26, name: 'seat 2', row: 'C', column: '2' },
    { id: 27, name: 'seat 3', row: 'C', column: '3' },
    { id: 28, name: 'seat 4', row: 'C', column: '4' },
    { id: 29, name: 'seat 5', row: 'C', column: '5' },
    { id: 30, name: 'seat 6', row: 'C', column: '6' },
    { id: 31, name: 'seat 7', row: 'C', column: '7' },
    { id: 32, name: 'seat 8', row: 'C', column: '8' },
    { id: 33, name: 'seat 9', row: 'C', column: '9' },
    { id: 34, name: 'seat 10', row: 'C', column: '10' },
    { id: 35, name: 'seat 11', row: 'C', column: '11' },
    { id: 36, name: 'seat 12', row: 'C', column: '12' },

    { id: 37, name: 'seat 1', row: 'D', column: '1' },
    { id: 38, name: 'seat 2', row: 'D', column: '2' },
    { id: 39, name: 'seat 3', row: 'D', column: '3' },
    { id: 40, name: 'seat 4', row: 'D', column: '4' },
    { id: 41, name: 'seat 5', row: 'D', column: '5' },
    { id: 42, name: 'seat 6', row: 'D', column: '6' },
    { id: 43, name: 'seat 7', row: 'D', column: '7' },
    { id: 44, name: 'seat 8', row: 'D', column: '8' },
    { id: 45, name: 'seat 9', row: 'D', column: '9' },
    { id: 46, name: 'seat 10', row: 'D', column: '10' },
    { id: 47, name: 'seat 11', row: 'D', column: '11' },
    { id: 48, name: 'seat 12', row: 'D', column: '12' },

    { id: 49, name: 'seat 1', row: 'E', column: '1' },
    { id: 50, name: 'seat 2', row: 'E', column: '2' },
    { id: 51, name: 'seat 3', row: 'E', column: '3' },
    { id: 52, name: 'seat 4', row: 'E', column: '4' },
    { id: 53, name: 'seat 5', row: 'E', column: '5' },
    { id: 54, name: 'seat 6', row: 'E', column: '6' },
    { id: 55, name: 'seat 7', row: 'E', column: '7' },
    { id: 56, name: 'seat 8', row: 'E', column: '8' },
    { id: 57, name: 'seat 9', row: 'E', column: '9' },
    { id: 58, name: 'seat 10', row: 'E', column: '10' },
    { id: 59, name: 'seat 11', row: 'E', column: '11' },
    { id: 60, name: 'seat 12', row: 'E', column: '12' },

    { id: 61, name: 'seat 1', row: 'F', column: '1' },
    { id: 62, name: 'seat 2', row: 'F', column: '2' },
    { id: 63, name: 'seat 3', row: 'F', column: '3' },
    { id: 64, name: 'seat 4', row: 'F', column: '4' },
    { id: 65, name: 'seat 5', row: 'F', column: '5' },
    { id: 66, name: 'seat 6', row: 'F', column: '6' },
    { id: 67, name: 'seat 7', row: 'F', column: '7' },
    { id: 68, name: 'seat 8', row: 'F', column: '8' },
    { id: 69, name: 'seat 9', row: 'F', column: '9' },
    { id: 70, name: 'seat 10', row: 'F', column: '10' },
    { id: 71, name: 'seat 11', row: 'F', column: '11' },
    { id: 72, name: 'seat 12', row: 'F', column: '12' },

    { id: 73, name: 'seat 1', row: 'G', column: '1' },
    { id: 74, name: 'seat 2', row: 'G', column: '2' },
    { id: 75, name: 'seat 3', row: 'G', column: '3' },
    { id: 76, name: 'seat 4', row: 'G', column: '4' },
    { id: 77, name: 'seat 5', row: 'G', column: '5' },
    { id: 78, name: 'seat 6', row: 'G', column: '6' },
    { id: 79, name: 'seat 7', row: 'G', column: '7' },
    { id: 80, name: 'seat 8', row: 'G', column: '8' },
    { id: 81, name: 'seat 9', row: 'G', column: '9' },
    { id: 82, name: 'seat 10', row: 'G', column: '10' },
    { id: 83, name: 'seat 11', row: 'G', column: '11' },
    { id: 84, name: 'seat 12', row: 'G', column: '12' },

    { id: 85, name: 'seat 1', row: 'H', column: '1' },
    { id: 86, name: 'seat 2', row: 'H', column: '2' },
    { id: 87, name: 'seat 3', row: 'H', column: '3' },
    { id: 88, name: 'seat 4', row: 'H', column: '4' },
    { id: 89, name: 'seat 5', row: 'H', column: '5' },
    { id: 90, name: 'seat 6', row: 'H', column: '6' },
    { id: 91, name: 'seat 7', row: 'H', column: '7' },
    { id: 92, name: 'seat 8', row: 'H', column: '8' },
    { id: 93, name: 'seat 9', row: 'H', column: '9' },
    { id: 94, name: 'seat 10', row: 'H', column: '10' },
    { id: 95, name: 'seat 11', row: 'H', column: '11' },
    { id: 96, name: 'seat 12', row: 'H', column: '12' },

    { id: 97, name: 'seat 1', row: 'I', column: '1' },
    { id: 98, name: 'seat 2', row: 'I', column: '2' },
    { id: 99, name: 'seat 3', row: 'I', column: '3' },
    { id: 100, name: 'seat 4', row: 'I', column: '4' },
    { id: 101, name: 'seat 5', row: 'I', column: '5' },
    { id: 102, name: 'seat 6', row: 'I', column: '6' },
    { id: 103, name: 'seat 7', row: 'I', column: '7' },
    { id: 104, name: 'seat 8', row: 'I', column: '8' },
    { id: 105, name: 'seat 9', row: 'I', column: '9' },
    { id: 106, name: 'seat 10', row: 'I', column: '10' },
    { id: 107, name: 'seat 11', row: 'I', column: '11' },
    { id: 108, name: 'seat 12', row: 'I', column: '12' },

    { id: 109, name: 'seat 1', row: 'J', column: '1' },
    { id: 110, name: 'seat 2', row: 'J', column: '2' },
    { id: 111, name: 'seat 3', row: 'J', column: '3' },
    { id: 112, name: 'seat 4', row: 'J', column: '4' },
    { id: 113, name: 'seat 5', row: 'J', column: '5' },
    { id: 114, name: 'seat 6', row: 'J', column: '6' },
    { id: 115, name: 'seat 7', row: 'J', column: '7' },
    { id: 116, name: 'seat 8', row: 'J', column: '8' },
    { id: 117, name: 'seat 9', row: 'J', column: '9' },
    { id: 118, name: 'seat 10', row: 'J', column: '10' },
    { id: 119, name: 'seat 11', row: 'J', column: '11' },
    { id: 120, name: 'seat 12', row: 'J', column: '12' },

    { id: 121, name: 'seat 1', row: 'K', column: '1' },
    { id: 122, name: 'seat 2', row: 'K', column: '2' },
    { id: 123, name: 'seat 3', row: 'K', column: '3' },
    { id: 124, name: 'seat 4', row: 'K', column: '4' },
    { id: 125, name: 'seat 5', row: 'K', column: '5' },
    { id: 126, name: 'seat 6', row: 'K', column: '6' },
    { id: 127, name: 'seat 7', row: 'K', column: '7' },
    { id: 128, name: 'seat 8', row: 'K', column: '8' },
    { id: 129, name: 'seat 9', row: 'K', column: '9' },
    { id: 130, name: 'seat 10', row: 'K', column: '10' },
    { id: 131, name: 'seat 11', row: 'K', column: '11' },
    { id: 132, name: 'seat 12', row: 'K', column: '12' },

]